version: 0.2
env:
  secrets-manager:
    LOGIN: olumoviesapp/sonar:sonartoken
    HOST: olumoviesapp/sonar:HOST
    Organization: olumoviesapp/sonar:Organization
    Project: olumoviesapp/sonar:Project

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3-pip jq
      - pip3 install --upgrade pip
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
      - export PATH=$PATH:/path/to/sonar-scanner-4.6.2.2472-linux/bin/

  build:
    commands:
      # Run your Django tests here, replace with your actual test command
      - python manage.py test
      - sonar-scanner \
          -Dsonar.login=$LOGIN \
          -Dsonar.host.url=$HOST \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization \
          -Dsonar.sources=.  # Specify source code path if not inferred correctly
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then exit 1 ; fi  # Exit with error code 1 based on quality gate status
